services:
  - type: web
    name: skin-disease-detection-backend
    env: node
    buildCommand: cd backend && npm install && pip install -r requirements.txt
    startCommand: cd backend && node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: MODEL_PATH
        value: model/skin_cancer_model_optimized.tflite

  - type: web
    name: skin-disease-detection-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://skin-disease-detection-backend.onrender.com 