services:
  - type: web
    name: skin-disease-detection-backend
    env: python
    buildCommand: pip install -r requirements.txt && npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: MODEL_PATH
        value: model/skin_cancer_model_optimized.tflite
      - key: CORS_ORIGIN
        value: https://skin-disease-detection-frontend-kyr8fb2jj.vercel.app
    healthCheckPath: /api/health 